name: balls
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

workspace:
  - shared_physics
  - server

dependencies:
  flame: ^1.35.1
  flutter:
    sdk: flutter
  shared_physics:
    path: shared_physics

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
